name: 'Updates and runs a relay.sh workflow on commit'
description: 'This action will update and run a named workflow on the service from github'
inputs:
  relay_username:
    required: true
    description: "Username on the relay service (stored as a repo secret)"
  relay_password:
    required: true
    description: "Login password for relay (stored as a repo secret)"
  relay_workflow:
    required: true
    description: "Relay workflow name"
  relay_workflow_file:
    required: true
    description: "Relay workflow file"
  relay_workflow_run_parameters:
    required: false
    description: "Relay workflow run parameters"
outputs:
  reponse:
    description: "response message from the relay service"
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'link-2'
  color: 'purple'
