name: 'Update relay.sh workflow on commit'
description: 'This action will update a named workflow on the service from github'
inputs:
  relay_username:
    required: true
    description: "Username on the relay service (stored as a repo secret)"
  relay_password:
    required: true
    description: "Login password for relay (stored as a repo secret)"
  relay_workflowdir:
    required: true
    description: "Directory relative to the repository root to find relay workflows"
outputs:
  reponse:
    description: "response message from the relay service"
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'link-2'
  color: 'purple'
